services:
  - type: web
    name: chatbot-flask-backend
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
